dataset:
  name: SemSupDataset
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
  test_result_folder: ./test
  use_cache: true
  cache_dir: ./dataset_cache/semsup_SUM
  num_classes: 5
  class_weights: [438547425, 550420181, 879623750, 20980938, 3044807]  
  num_points: 65536
  # Taxonomy is Ground, Vegetation, Building, Street Element, Water
  ignored_label_inds:
    - 0
  datasets:
    -
      name: SUMDataset
      dataset_path: data/datasets/SUM/1.0/SUM_Helsinki_C6_pcl_30
      train_files: train/*
      val_files: validate/*
      test_files: test/*
      class_map:
        1: 1
        2: 2
        3: 3
        4: 5
        5: 4
        6: 0
    -
      name: TurinDataset3D
      dataset_path: data/digitwin/sansalvario_crop
      num_points: 65536
      train_dir: Lidar_consegna
      val_dir: Lidar_consegna
      test_dir: Lidar_consegna
      offset: [396000, 4989500, 0]
model:
  name: RandLANetMixer
  batcher: DefaultBatcher
  ckpt_path: test/train_randlanet_sensat_SUM_augs_augs_4gro_3bui/checkpoint/ckpt_00200.pth
  load_optimizer: false
  load_scheduler: false
  num_neighbors: 16
  ema: 0.99
  num_layers: 5
  num_points: 65536
  num_classes: 5
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.2
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
    RandomHorizontalFlip:
      axes: [0, 1]
    ChromaticJitter:
      std: 0.01
    HueSaturationTranslation:
      hue_max: 0.5
      saturation_max: 0.2
pipeline:
  name: SemiSupervisedSegmentation
  optimizer:
    lr: 0.0005
  batch_size: 4
  main_log_dir: ./test
  max_epoch: 200
  ema_start_epoch: 0
  confidence_th: 0.80
  save_ckpt_freq: 20
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: ./test
  num_workers: 0
  pin_memory: false
  val_batch_size: 4
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
