name: ECLAIRDataset
cache_dir: ./dataset_cache
dataset_path: data/digitwin/ECLAIR
class_weights: []
ignored_label_inds: [0,1]
num_classes: 10
num_points: 65536
train_files: train.txt
val_files: val.txt
test_files: test.txt
test_result_folder: ./test
use_cache: true
steps_per_epoch_train: 100
steps_per_epoch_valid: 10