dataset:
  name: ECLAIRDataset
  cache_dir: ./dataset_cache
  dataset_path: data/digitwin/ECLAIR
  class_weights: []
  ignored_label_inds: [0,1]
  num_classes: 10
  num_points: 65536
  train_files: train.txt
  val_files: val.txt
  test_files: test.txt
  test_result_folder: ./test
  use_cache: true
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 10
  ignored_label_inds: [0,1]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.05
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 5
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  num_workers: 0
  pin_memory: false
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
