name: TurinDataset3D
cache_dir: ./dataset_cache/turin_bin
dataset_path: data/digitwin/sansalvario_crop
class_weights: [1,1]
num_classes: 2
num_points: 65536
train_dir: Lidar_consegna
val_dir: Lidar_consegna
test_dir: Lidar_consegna
test_result_folder: ./test
use_cache: true
steps_per_epoch_train: 100
steps_per_epoch_valid: 10
offset: [396000, 4989500, 0]