dataset:
  name: TurinDataset3D
  cache_dir: ./dataset_cache/turin_ground
  dataset_path: data/digitwin/sansalvario_crop
  class_weights: [1604601037,438547425, 49452238,26669467,  43503086, 174125]
  num_classes: 6
  num_points: 65536
  test_dir: lidar_ground
  test_result_folder: ./logs
  train_dir: lidar_ground
  use_cache: true
  val_dir: lidar_ground
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: ./logs/train_randlanet_only_groundpoints/checkpoint/ckpt_00020.pth
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 6
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.2
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 5
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  num_workers: 0
  pin_memory: false
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
