dataset:
  name: TurinDataset3D
  cache_dir: ./dataset_cache
  dataset_path: data/digitwin/sansalvario_crop
  class_weights: [1,1,1,1]
  num_classes: 4
  num_points: 65536
  test_dir: Lidar_consegna
  test_result_folder: ./test
  train_dir: Lidar_consegna
  use_cache: true
  val_dir: Lidar_consegna
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: ./logs/train_randlanet_sensat_4class/checkpoint/ckpt_00200.pth
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 4
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 5
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  num_workers: 0
  pin_memory: false
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
