dataset:
  name: TurinDataset3D
  cache_dir: ./dataset_cache
  dataset_path: /nfs/home/intini/Open3D-ML/test/turin_confidence_iter0/dataset
  class_weights: [1, 1, 1, 1, 1,1]
  num_classes: 6
  num_points: 65536
  ignored_label_inds: [0]
  test_dir: train
  test_result_folder: ./test
  train_dir: train
  use_cache: true
  val_dir: val
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path:
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 6
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  use_confidence: true
  confidence: {1: 0.1, 2: 0.6, 3: 0.8, 4: 0.8, 5: 0.5, 6: 0.9 }
  # confidence: {1: 0.1, 2: 0.1, 3: 0.1, 4: 0.1, 5: 0.1, 6: 0.1 }
  in_channels: 7
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.2
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
    rotate:
      method: all
    RandomHorizontalFlip:
      axes: [0,1]
    ChromaticAutoContrast:
      prob: 0.1
    ChromaticJitter:
      std: 0.008
    HueSaturationTranslation:
      hue_max: 0.3
      saturation_max: 0.1
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 4
  main_log_dir: ./test
  max_epoch: 100
  save_ckpt_freq: 1
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: ./test
  val_batch_size: 4
  num_workers: 0
  pin_memory: false
