dataset:
  name: ConcatDataset
  steps_per_epoch_train: 4
  steps_per_epoch_valid: 4
  test_result_folder: ./logs
  cache_dir: ./dataset_cache/sensat_test
  class_weights: [579547289, 550856858, 904143863, 340505589, 708884]
  num_classes: 5
  use_cache: true 
  sampler:
        name: SemSegRandomClassSampler
  ignored_label_inds:
    - 0
  datasets:
    - 
      name: SensatUrban
      dataset_path: data/digitwin/sensatUrban/ply
      sampler:
        name: SemSegRandomClassSampler
      num_points: 65536  
      # Taxonomy is Ground, Vegetation, Building, Street Element, Water
      class_map:
        0: 1
        1: 2
        2: 3
        3: 3
        4: 4
        5: 1
        6: 4
        7: 1
        8: 4
        9: 4
        10: 4
        11: 4
        12: 5
      train_files:
        - train/birmingham_block_10.ply
        - train/birmingham_block_11.ply

      val_files:
        - train/birmingham_block_1.ply
      test_files:
        - test/birmingham_block_2.ply
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 5
  sampler:
    name: SemSegRandomClassSampler
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.2
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 4
  main_log_dir: ./test
  max_epoch: 2
  save_ckpt_freq: 20
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: ./test
  num_workers: 0
  pin_memory: false
  val_batch_size: 4
  summary:
    record_for: ["valid"]
    max_pts:
    use_reference: false
    max_outputs: 1