dataset:
  name: TurinDataset3D
  cache_dir: ./dataset_cache
  dataset_path: data/digitwin/sansalvario_crop
  class_weights: [41697357, 1745448, 6572572, 19136493, 674897, 897825, 4634634, 374721]
  ignored_label_inds:
  - 0
  num_classes: 8
  num_points: 65536
  train_dir: Lidar_consegna
  val_dir: Lidar_consegna
  test_dir: Lidar_consegna
  test_result_folder: ./test
  use_cache: true
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
  offset: [396000, 4989500, 0]
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: data/digitwin/models/randlanet_sensat_5cls_ckpt_00458.pth
  return_features: true
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 5
  ignored_label_inds: []
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.2
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
pipeline:
  name: FeatureExtraction
  optimizer:
    lr: 0.01
  batch_size: 4
  main_log_dir: ./logs
  test_batch_size: 1
  train_sum_dir: train_log
  num_workers: 0
  pin_memory: false
  val_batch_size: 2
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1