dataset:
  name: ConcatDataset
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
  num_classes: 4
  cache_dir: ./dataset_cache
  ignored_label_inds: []
  class_weights: [1,1,1,1]
  datasets:
    -
      name: Toronto3D
      dataset_path: data/digitwin/Toronto3D
      num_classes: 4
      num_points: 65536
      class_map: #0: ground & vegetation, 1: artificial buildings , 2: water, 3: objects
        0: 3
        1: 1
        2: 1
        3: 0
        4: 1
        5: 1
        6: 3
        7: 3
        8: 3
      test_files:
      - L002.ply
      test_result_folder: ./test
      train_files:
      - L001.ply
      - L003.ply
      - L004.ply
      use_cache: true
      val_files:
      - L002.ply
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: logs/train_randlanet_sensat_4class/checkpoint/ckpt_00200.pth
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 4
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  ignored_label_inds: []
  in_channels: 6
  dim_input: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.05
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 5
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  num_workers: 0
  pin_memory: false
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
