dataset:
  name: ConcatDataset
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
  test_result_folder: ./test
  cache_dir: ./dataset_cache/concat_baseline/pointtransformer_aug_all
  class_weights: [831613596, 319885857, 1534944055, 2604888915, 137576607, 361131880]
  num_classes: 6
  num_points: 65536
  # Taxonomy is Soil, Terrain, Vegetation, Building, Street Element, Water
  ignored_label_inds:
    - 0
  use_cache: true
  datasets:
    - name: SUMDataset
      dataset_path: data/digitwin/SUM/1.0/SUM_Helsinki_C6_pcl_300
      train_files: train/*
      val_files: validate/*
      test_files: test/*
      class_map:
        1: 0
        2: 3
        3: 4
        4: 6
        5: 5
        6: 0
    - name: SensatUrban
      dataset_path: data/digitwin/sensatUrban/ply
      class_map:
        0: 1
        1: 3
        2: 4
        3: 4
        4: 2
        5: 2
        6: 2
        7: 2
        8: 5
        9: 5
        10: 2
        11: 5
        12: 6
      train_files:
        - train/birmingham_block_10.ply
        - train/birmingham_block_11.ply
        - train/birmingham_block_12.ply
        - train/birmingham_block_13.ply
        - train/birmingham_block_3.ply
        - train/birmingham_block_4.ply
        - train/birmingham_block_6.ply
        - train/cambridge_block_12.ply
        - train/cambridge_block_13.ply
        - train/cambridge_block_14.ply
        - train/cambridge_block_17.ply
        - train/cambridge_block_18.ply
        - train/cambridge_block_19.ply
        - train/cambridge_block_2.ply
        - train/cambridge_block_20.ply
        - train/cambridge_block_21.ply
        - train/cambridge_block_23.ply
        - train/cambridge_block_25.ply
        - train/cambridge_block_26.ply
        - train/cambridge_block_28.ply
        - train/cambridge_block_3.ply
        - train/cambridge_block_32.ply
        - train/cambridge_block_33.ply
        - train/cambridge_block_4.ply
        - train/cambridge_block_6.ply
        - train/birmingham_block_0.ply
        - train/birmingham_block_7.ply
        - train/birmingham_block_9.ply
        - train/cambridge_block_8.ply
        - train/cambridge_block_9.ply
      val_files:
        - train/birmingham_block_1.ply
        - train/birmingham_block_5.ply
        - train/cambridge_block_10.ply
        - train/cambridge_block_7.ply
      test_files:
        - test/birmingham_block_2.ply
        - test/birmingham_block_8.ply
        - test/cambridge_block_15.ply
        - test/cambridge_block_22.ply
        - test/cambridge_block_16.ply
        - test/cambridge_block_27.ply
    - name: Toronto3D
      dataset_path: data/digitwin/Toronto3D
      class_map:
        1: 1
        2: 1
        3: 3
        4: 4
        5: 5
        6: 5
        7: 5
        8: 4
      test_files:
        - L002.ply
      train_files:
        - L001.ply
        - L003.ply
        - L004.ply
      val_files:
        - L002.ply
    - name: ECLAIRDataset
      dataset_path: data/digitwin/ECLAIR
      train_files: train.txt
      val_files: val.txt
      test_files: test.txt
      class_map:
        0: 0
        1: 0
        2: 0
        3: 3
        4: 4
        5: 0
        6: 5
        7: 5
        8: 5
        9: 4
        10: 4
        11: 5
    - name: FRACTALDataset
      dataset_path: data/digitwin/FRACTAL/extracted_data
      train_dir: train
      val_dir: val
      test_dir: test
      class_map:
        1: 0
        2: 0
        3: 1
        4: 3
        5: 3
        6: 4
        9: 6
        17: 2
        64: 5
        65: 0
        66: 0
    - name: STPLS3D
      dataset_path: data/digitwin/STPLS3D
      class_map:
        0: 2
        1: 4
        2: 3
        3: 3
        4: 3
        5: 5
        6: 5
        7: 5
        8: 5
        9: 5
        10: 5
        11: 5
        12: 5
        13: 5
        14: 4
        15: 2
        17: 4
        18: 1
        19: 1
      train_files:
        - RealWorldData/OCCC_points.ply
        - RealWorldData/RA_points.ply
        - Synthetic_v3/1_points_GTv3.ply
        - Synthetic_v3/2_points_GTv3.ply
        - Synthetic_v3/3_points_GTv3.ply
        - Synthetic_v3/4_points_GTv3.ply
        - Synthetic_v3/5_points_GTv3.ply
        - Synthetic_v3/6_points_GTv3.ply
        - Synthetic_v3/7_points_GTv3.ply
        - Synthetic_v3/8_points_GTv3.ply
        - Synthetic_v3/9_points_GTv3.ply
        - Synthetic_v3/10_points_GTv3.ply
        - Synthetic_v3/11_points_GTv3.ply
        - Synthetic_v3/12_points_GTv3.ply
        - Synthetic_v3/13_points_GTv3.ply
        - Synthetic_v3/14_points_GTv3.ply
        - Synthetic_v3/15_points_GTv3.ply
        - Synthetic_v3/16_points_GTv3.ply
        - Synthetic_v3/17_points_GTv3.ply
        - Synthetic_v3/18_points_GTv3.ply
        - Synthetic_v3/19_points_GTv3.ply
      val_files:
        - RealWorldData/USC_points.ply
        - Synthetic_v3/20_points_GTv3.ply
        - Synthetic_v3/21_points_GTv3.ply
        - Synthetic_v3/22_points_GTv3.ply
      test_files:
        - RealWorldData/WMSC_points.ply
        - Synthetic_v3/1_points_GTv3.ply
        - Synthetic_v3/23_points_GTv3.ply
        - Synthetic_v3/24_points_GTv3.ply
        - Synthetic_v3/25_points_GTv3.ply
    - name: Swiss3D
      dataset_path: data/digitwin/Swiss3D/Medium
      class_map:
        1: 0
        2: 4
        3: 5
        4: 3
        5: 5
      train_files:
        - 13_Zurich_16_34318_-22951.ply
        - 14_Zurich_16_34319_-22951.ply
        - 15_Zurich_16_34319_-22952.ply
        - 16_Zurich_16_34322_-22951.ply
        - 3_Davos_16_34557_-23105.ply
        - 4_Davos_16_34558_-23104.ply
        - 5_Davos_16_34558_-23105.ply
        - 10_Zug_16_34320_-23004.ply
        - 6_Zug_16_34307_-23001.ply
        - 7_Zug_16_34307_-23002.ply
      val_files:
        - 12_Zurich_16_34318_-22950.ply
        - 2_Davos_16_34557_-23104.ply
        - 8_Zug_16_34308_-23001.ply
      test_files:
        - 9_Zug_16_34308_-23002.ply
        - 11_Zurich_16_34317_-22952.ply
        - 1_Davos_16_34556_-23105.ply
    - name: HessigheimDataset
      dataset_path: data/digitwin/Hessigheim/March2018
      train_dir: training
      val_dir: validation
      test_dir: test
      class_map:
        0: 1
        1: 2
        2: 5
        3: 5
        4: 4
        5: 4
        6: 3
        7: 3
        8: 1
        9: 4
        10: 4

model:
  name: PointTransformer
  batcher: ConcatBatcher
  ckpt_path: # path/to/your/checkpoint
  in_channels: 6
  blocks: [2, 3, 4, 6, 3]
  num_classes: 6
  voxel_size: 0.2 # default is 0.04
  max_voxels: 65536 # default is 50000
  ignored_label_inds:
    - 0
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
    rotate:
      method: all
    RandomHorizontalFlip:
      axes: [0,1]
    ChromaticAutoContrast:
      prob: 0.1
    ChromaticJitter:
      std: 0.008
    HueSaturationTranslation:
      hue_max: 0.3
      saturation_max: 0.1
 
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 4
  main_log_dir: ./test
  max_epoch: 200
  save_ckpt_freq: 20
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: ./test
  num_workers: 0
  pin_memory: false
  val_batch_size: 2

